"""
Claude Agent — Interacts with Anthropic's Claude API.

Handles:
  - Sending prompts with text + images (Claude Vision)
  - Streaming responses
  - Parsing structured output (file blocks)
"""

import anthropic
from dataclasses import dataclass
from config import Config
from rich.console import Console
from rich.progress import Progress, SpinnerColumn, TextColumn

console = Console()


@dataclass
class GeneratedFile:
    """A single file generated by Claude."""

    path: str
    content: str
    language: str = ""


class ClaudeAgent:
    """
    Agentic interface to Claude API.
    Sends combined context and parses structured file output.
    """

    def __init__(self):
        self.client = anthropic.Anthropic(api_key=Config.ANTHROPIC_API_KEY)
        self.model = Config.CLAUDE_MODEL
        self.max_tokens = Config.CLAUDE_MAX_TOKENS

    def generate_code(
        self,
        prompt: str,
        image_base64: str | None = None,
        image_media_type: str = "image/png",
    ) -> list[GeneratedFile]:
        """
        Send prompt (+ optional Figma screenshot) to Claude.
        Returns a list of GeneratedFile objects parsed from the response.

        Args:
            prompt: The full combined prompt text
            image_base64: Optional base64-encoded image (Figma screenshot)
            image_media_type: MIME type of the image
        """
        console.print("\n[bold cyan]🤖 Sending to Claude Agent...[/bold cyan]")
        console.print(f"[dim]   Model: {self.model}[/dim]")
        console.print(f"[dim]   Max tokens: {self.max_tokens}[/dim]")

        # Build message content
        content = []

        # Add image if provided (Claude Vision)
        if image_base64:
            content.append({
                "type": "image",
                "source": {
                    "type": "base64",
                    "media_type": image_media_type,
                    "data": image_base64,
                },
            })
            console.print("[dim]   📷 Figma screenshot attached[/dim]")

        # Add text prompt
        content.append({"type": "text", "text": prompt})

        # Call Claude API with streaming
        response_text = ""

        with Progress(
            SpinnerColumn(),
            TextColumn("[cyan]{task.description}[/cyan]"),
            console=console,
        ) as progress:
            task = progress.add_task("Claude is generating code...", total=None)

            try:
                with self.client.messages.stream(
                    model=self.model,
                    max_tokens=self.max_tokens,
                    messages=[{"role": "user", "content": content}],
                    system="You are a senior full-stack developer. Generate production-ready, complete code. Always use the ===FILE: path=== and ===END FILE=== markers for each file.",
                ) as stream:
                    for text in stream.text_stream:
                        response_text += text
                        # Update progress with character count
                        progress.update(
                            task,
                            description=f"Claude is generating code... ({len(response_text)} chars)",
                        )

            except anthropic.APIConnectionError:
                console.print("[red]❌ Cannot connect to Anthropic API[/red]")
                return []
            except anthropic.AuthenticationError:
                console.print("[red]❌ Invalid ANTHROPIC_API_KEY — check your .env file[/red]")
                return []
            except anthropic.RateLimitError:
                console.print("[red]❌ Rate limited — wait a moment and try again[/red]")
                return []
            except Exception as e:
                console.print(f"[red]❌ Claude API error: {e}[/red]")
                return []

        # Parse the response into files
        files = self._parse_file_blocks(response_text)

        if files:
            console.print(f"\n[bold green]✅ Claude generated {len(files)} files:[/bold green]")
            for f in files:
                console.print(f"   📄 {f.path}")
        else:
            console.print("[yellow]⚠️ No file blocks found in response. Showing raw output:[/yellow]")
            console.print(response_text[:2000])

        return files

    def chat(self, prompt: str) -> str:
        """Simple chat with Claude — returns text response."""
        try:
            message = self.client.messages.create(
                model=self.model,
                max_tokens=self.max_tokens,
                messages=[{"role": "user", "content": prompt}],
            )
            return message.content[0].text
        except Exception as e:
            console.print(f"[red]❌ Claude API error: {e}[/red]")
            return ""

    def _parse_file_blocks(self, text: str) -> list[GeneratedFile]:
        """
        Parse Claude's response to extract file blocks.

        Expected format in response:
            ===FILE: src/types/user.ts===
            ```typescript
            // code here
            ```
            ===END FILE===
        """
        files = []
        lines = text.split("\n")
        i = 0

        while i < len(lines):
            line = lines[i].strip()

            # Look for ===FILE: path=== marker
            if line.startswith("===FILE:") and line.endswith("==="):
                file_path = line[8:-3].strip()
                code_lines = []
                language = ""
                i += 1

                # Skip opening ``` marker and capture language
                while i < len(lines):
                    stripped = lines[i].strip()
                    if stripped.startswith("```"):
                        language = stripped[3:].strip()
                        i += 1
                        break
                    elif stripped == "===END FILE===":
                        break
                    i += 1

                # Capture code content until closing ``` or ===END FILE===
                while i < len(lines):
                    stripped = lines[i].strip()
                    if stripped == "```" or stripped == "===END FILE===":
                        i += 1
                        # Skip to ===END FILE=== if we hit ```
                        if stripped == "```":
                            while i < len(lines) and lines[i].strip() != "===END FILE===":
                                i += 1
                        break
                    code_lines.append(lines[i])  # Keep original indentation
                    i += 1

                if code_lines:
                    # Detect language from file extension if not set
                    if not language:
                        language = self._detect_language(file_path)
                    files.append(GeneratedFile(
                        path=file_path,
                        content="\n".join(code_lines),
                        language=language,
                    ))
            i += 1

        return files

    @staticmethod
    def _detect_language(file_path: str) -> str:
        """Detect programming language from file extension."""
        ext_map = {
            ".ts": "typescript",
            ".tsx": "typescriptreact",
            ".js": "javascript",
            ".jsx": "javascriptreact",
            ".py": "python",
            ".css": "css",
            ".scss": "scss",
            ".json": "json",
            ".html": "html",
            ".yaml": "yaml",
            ".yml": "yaml",
            ".md": "markdown",
            ".sql": "sql",
        }
        for ext, lang in ext_map.items():
            if file_path.endswith(ext):
                return lang
        return ""
